#!/bin/bash
set -euo pipefail

source $(dirname $0)/env.sh

echo "> Building pinocchio_sol_vault_program..."
cd $PROJECT_ROOT/programs/pinocchio_sol_vault_program
cargo build-sbf

echo "> Building pinocchio_sol_vault_client..."
cd $PROJECT_ROOT/clients/rust/pinocchio_sol_vault_client
cargo build -p pinocchio_sol_vault_client

echo "> Build complete!"
