#!/bin/bash
set -euo pipefail

source $(dirname $0)/env.sh
cd $PROJECT_ROOT

./scripts/build-pinocchio-counter

echo "> Unit testing pinocchio_counter_program..."
cd $PROJECT_ROOT/programs/pinocchio_counter_program
cargo test-sbf
cd $PROJECT_ROOT

echo "> Unit testing pinocchio_counter_client..."
cargo test -p pinocchio_counter_client

echo "> Integration testing pinocchio_counter..."
cargo test -p integration-tests pinocchio_counter

echo "> Test complete!"